name: Homebrew Doctor

on: [push]

jobs:
  doctor:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Brew doctor
        run: |
          brew tap pp-spaces/khmer-fonts
